language: node_js
node_js:
  - "8"
  - "7"
  - "6"
install:
  - npm install
script: npm run test-ci
after_success: 
  - npm run coveralls
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website && npm install && GIT_USER="${GH_NAME}" npm run publish-gh-pages
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a2a0553efb6f410c8c13
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always