// import './check'
// import './classes'
// import './color'
// import './counter-chain-reaction'
// import './counter-plural'
// import './counter'
// import './hello'
// import './model'
// import './mounting'
// import './show'
// import './template'
// import './unmount'
// import './unmountTmpl'
import './template-test'
